package ua.com.my_pocket.user_database.validation_user;

public interface ValidatorMessegesRegistration {

	String IDENTIFICATION_ID_NO_EXIST = "IDENTIFICATION_ID_NO_EXIST";
	String NAME_NO_EXIST = "NAME_NO_EXIST";
	String SURNAME_NO_EXIST = "SURNAME_NO_EXIST";
	String DADNAME_NO_EXIST = "DADNAME_NO_EXIST";

	String EMAIL_ALREADY_EXIST = "EMAIL_ALREADY_EXIST";
	String PHONE_ALREADY_EXIST = "PHONE_ALREADY_EXIST";
	String IDENTIFICATION_ALREADY_EXIST = "IDENTIFICATION_ALREADY_EXIST";

	String EMPTY_IDENTIFICATION_ID_FIELD = "EMPTY_IDENTIFICATION_ID_FIELD";
	String EMPTY_NAME_FIELD = "EMPTY_NAME_FIELD";
	String EMPTY_SURNAME_FIELD = "EMPTY_SURNAME_FIELD";
	String EMPTY_DADNAME_FIELD = "EMPTY_DADNAME_FIELD";
	String EMPTY_EMAIL_FIELD = "EMPTY_EMAIL_FIELD";
	String EMPTY_PASSWORD_FIELD = "EMPTY_PASSWORD_FIELD";
	String EMPTY_PHONE_FIELD = "EMPTY_PHONE_FIELD";

}
