package ua.com.my_pocket.user_database.validation_state;

public interface ValidatorMessegeState {

	String EMPTY_IDENTIFICATION_ID_FIELD = "EMPTY_IDENTIFICATION_ID_FIELD";
	String EMPTY_SERIA_FIELD = "EMPTY_SERIA_FIELD";
	String EMPTY_CODE_FIELD = "EMPTY_CODE_FIELD";
	String EMPTY_NAME_FIELD = "EMPTY_NAME_FIELD";
	String EMPTY_SURNAME_FIELD = "EMPTY_SURNAME_FIELD";
	String EMPTY_DADNAME_FIELD = "EMPTY_DADNAME_FIELD";

	String IDENTIFICATION_ID_EXIST = "IDENTIFICATION_ID_EXIST";
}
